### ISSUE TITLE
`FileNotFoundError` in `poetry build`

### ISSUE THREAD

**Issue by Vilin97** [stanford-centaur/PyPantograph#67]
I am running into the following error when installing PyPantograph:
```
C:\Users\Vasily\Github\PyPantograph>poetry build
Creating virtualenv pantograph-zuw5teR0-py3.12 in C:\Users\Vasily\AppData\Local\pypoetry\Cache\virtualenvs
Preparing build environment with build-system requirements poetry-core
Building pantograph (0.2.24)
  - Building sdist
  - Built pantograph-0.2.24.tar.gz
  - Building wheel
Traceback (most recent call last):
  File "C:\Users\Vasily\Github\PyPantograph\build.py", line 10, in <module>
    with subprocess.Popen(["lake", "build", "repl"], cwd=PATH_PANTOGRAPH) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

Command '['C:/Users/Vasily/AppData/Local/Temp/tmp592xfxlv/.venv/Scripts/python.exe', 'build.py']' returned non-zero exit status 1.
```

**Comment by lenianiva** [comment]
Looks like `lake` is not available. Install `lake` by first installing `elan`. Then check if `~/.elan` is in your `$PATH`.

**Comment by Vilin97** [comment]
Both are on the path now. Still getting the same error.

**Comment by lenianiva** [comment]
I looked this up and the `_winapi` bit seems to be a Windows-specific issue. I don't know how to use windows

**Comment by Vilin97** [comment]
I just renamed `repl.exe` to `repl` in `src/.lake/build/bin/` and it resolved the issue! Maybe this should be added to the install instructions? Or maybe you can make `repl` in addition to the existing `repl.exe`?

**Comment by lenianiva** [comment]
yeah that should fix it.

Could you also see if the same issue is causing the other error?

**Comment by attilajam** [comment]
@lenianiva, me and @Vilin97 were working on the same project and I was on Linux and he was on Windows. This fix did not fix the other error, but I think it may have to do with the way that Windows handles Python interpreters, as it's not able to select the poetry version of the interpreter if I understand how it works correctly.
